# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoWindow(object):
    def setupUi(self, InfoWindow):
        InfoWindow.setObjectName("InfoWindow")
        InfoWindow.resize(418, 302)
        InfoWindow.setMinimumSize(QtCore.QSize(418, 0))
        InfoWindow.setMaximumSize(QtCore.QSize(418, 302))
        InfoWindow.setStyleSheet("background-color: rgb(69, 78, 89);")
        self.centralwidget = QtWidgets.QWidget(InfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(266, 227, 122, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: none;\n"
                                      "background-color: #3D89F6;\n"
                                      "color: white;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 311, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(220, 220, 220); ")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 382, 22))
        self.label_2.setStyleSheet("color: rgb(220, 220, 220); ")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 108, 22))
        self.label_3.setStyleSheet("color: rgb(220, 220, 220); ")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 359, 22))
        self.label_4.setStyleSheet("color: rgb(220, 220, 220); ")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(InfoWindow)
        QtCore.QMetaObject.connectSlotsByName(InfoWindow)

    def retranslateUi(self, InfoWindow):
        _translate = QtCore.QCoreApplication.translate
        InfoWindow.setWindowTitle(_translate("InfoWindow", "About"))
        self.pushButton.setText(_translate("InfoWindow", "Закрыть"))
        self.label.setText(_translate("InfoWindow", "Конвертор вещественных чисел"))
        self.label_2.setText(_translate("InfoWindow", "Осуществляет перевод из 10-ой СС в 2-ую."))
        self.label_3.setText(_translate("InfoWindow", "И наоборот."))
        self.label_4.setText(_translate("InfoWindow", "Разработчик: Асадуллин Тагир. ИУ7-24Б"))
