# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/source/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(456, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(456, 730))
        MainWindow.setMaximumSize(QtCore.QSize(456, 730))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setAcceptDrops(True)
        MainWindow.setToolTip("")
        MainWindow.setToolTipDuration(-5)
        MainWindow.setStatusTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(69, 78, 89); color:white;")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.to2 = QtWidgets.QRadioButton(self.centralwidget)
        self.to2.setGeometry(QtCore.QRect(114, 39, 96, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.to2.setFont(font)
        self.to2.setAutoFillBackground(False)
        self.to2.setStyleSheet("QRadioButton{ \n"
"    color: white;\n"
"}\n"
"QRadioButton::indicator \n"
"{\n"
"   border: 1px solid black;\n"
"background: #d7d7d7;\n"
"\n"
"}\n"
"QRadioButton::indicator:checked \n"
"{\n"
"    background: #85bf2d;\n"
"   border: 1px solid black;\n"
"\n"
"}")
        self.to2.setChecked(True)
        self.to2.setAutoRepeat(False)
        self.to2.setObjectName("to2")
        self.radio_group = QtWidgets.QButtonGroup(MainWindow)
        self.radio_group.setObjectName("radio_group")
        self.radio_group.addButton(self.to2)
        self.to10 = QtWidgets.QRadioButton(self.centralwidget)
        self.to10.setGeometry(QtCore.QRect(264, 39, 96, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.to10.setFont(font)
        self.to10.setStyleSheet("QRadioButton{ \n"
"color: white;\n"
"}\n"
"QRadioButton::indicator \n"
"{\n"
"   border: 1px solid black;\n"
"background:#d7d7d7;\n"
"\n"
"}\n"
"QRadioButton::indicator:checked \n"
"{\n"
"    background: #85bf2d;\n"
"   border: 1px solid black;\n"
"\n"
"}")
        self.to10.setChecked(False)
        self.to10.setObjectName("to10")
        self.radio_group.addButton(self.to10)
        self.enter_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_bar.setGeometry(QtCore.QRect(34, 99, 391, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.enter_bar.setFont(font)
        self.enter_bar.setMouseTracking(False)
        self.enter_bar.setTabletTracking(False)
        self.enter_bar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.enter_bar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.enter_bar.setAutoFillBackground(False)
        self.enter_bar.setStyleSheet("background-color: rgb(171, 217, 102);\n"
"color: #688C32;\n"
"border-radius: 1px;\n"
"\n"
"")
        self.enter_bar.setInputMask("")
        self.enter_bar.setText("")
        self.enter_bar.setMaxLength(24)
        self.enter_bar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enter_bar.setDragEnabled(False)
        self.enter_bar.setReadOnly(False)
        self.enter_bar.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.enter_bar.setClearButtonEnabled(True)
        self.enter_bar.setObjectName("enter_bar")
        self.num_1 = QtWidgets.QPushButton(self.centralwidget)
        self.num_1.setEnabled(True)
        self.num_1.setGeometry(QtCore.QRect(34, 269, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_1.setFont(font)
        self.num_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_1.setObjectName("num_1")
        self.nums = QtWidgets.QButtonGroup(MainWindow)
        self.nums.setObjectName("nums")
        self.nums.addButton(self.num_1)
        self.num_2 = QtWidgets.QPushButton(self.centralwidget)
        self.num_2.setEnabled(True)
        self.num_2.setGeometry(QtCore.QRect(134, 269, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_2.setFont(font)
        self.num_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_2.setObjectName("num_2")
        self.nums.addButton(self.num_2)
        self.num_3 = QtWidgets.QPushButton(self.centralwidget)
        self.num_3.setEnabled(True)
        self.num_3.setGeometry(QtCore.QRect(234, 269, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_3.setFont(font)
        self.num_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_3.setObjectName("num_3")
        self.nums.addButton(self.num_3)
        self.num_4 = QtWidgets.QPushButton(self.centralwidget)
        self.num_4.setEnabled(True)
        self.num_4.setGeometry(QtCore.QRect(34, 369, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_4.setFont(font)
        self.num_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_4.setObjectName("num_4")
        self.nums.addButton(self.num_4)
        self.num_5 = QtWidgets.QPushButton(self.centralwidget)
        self.num_5.setEnabled(True)
        self.num_5.setGeometry(QtCore.QRect(134, 369, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_5.setFont(font)
        self.num_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_5.setObjectName("num_5")
        self.nums.addButton(self.num_5)
        self.num_6 = QtWidgets.QPushButton(self.centralwidget)
        self.num_6.setEnabled(True)
        self.num_6.setGeometry(QtCore.QRect(234, 369, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_6.setFont(font)
        self.num_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_6.setObjectName("num_6")
        self.nums.addButton(self.num_6)
        self.num_8 = QtWidgets.QPushButton(self.centralwidget)
        self.num_8.setEnabled(True)
        self.num_8.setGeometry(QtCore.QRect(134, 469, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_8.setFont(font)
        self.num_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_8.setObjectName("num_8")
        self.nums.addButton(self.num_8)
        self.num_7 = QtWidgets.QPushButton(self.centralwidget)
        self.num_7.setEnabled(True)
        self.num_7.setGeometry(QtCore.QRect(34, 469, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_7.setFont(font)
        self.num_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_7.setObjectName("num_7")
        self.nums.addButton(self.num_7)
        self.num_9 = QtWidgets.QPushButton(self.centralwidget)
        self.num_9.setEnabled(True)
        self.num_9.setGeometry(QtCore.QRect(234, 469, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_9.setFont(font)
        self.num_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_9.setObjectName("num_9")
        self.nums.addButton(self.num_9)
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(34, 569, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.dot.setFont(font)
        self.dot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dot.setStyleSheet("background-color: rgb(148, 152, 159);\n"
"border: none;color: #FFFFFF;")
        self.dot.setObjectName("dot")
        self.nums.addButton(self.dot)
        self.num_0 = QtWidgets.QPushButton(self.centralwidget)
        self.num_0.setEnabled(True)
        self.num_0.setGeometry(QtCore.QRect(134, 569, 191, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.num_0.setFont(font)
        self.num_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_0.setStyleSheet("QPushButton {\n"
"    background-color: rgb(131, 143, 159);\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.num_0.setObjectName("num_0")
        self.nums.addButton(self.num_0)
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(334, 269, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.delete_2.setFont(font)
        self.delete_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_2.setStyleSheet("background-color: #EA6363;\n"
"border: none;color: #FFFFFF;")
        self.delete_2.setObjectName("delete_2")
        self.res_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.res_bar.setGeometry(QtCore.QRect(34, 199, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.res_bar.setFont(font)
        self.res_bar.setMouseTracking(False)
        self.res_bar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.res_bar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.res_bar.setAcceptDrops(True)
        self.res_bar.setStyleSheet("background-color: rgb(171, 217, 102);\n"
"color: #688C32;\n"
"border-top: 3px solid #454E59;")
        self.res_bar.setInputMask("")
        self.res_bar.setText("")
        self.res_bar.setFrame(True)
        self.res_bar.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.res_bar.setCursorPosition(0)
        self.res_bar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.res_bar.setDragEnabled(False)
        self.res_bar.setReadOnly(True)
        self.res_bar.setPlaceholderText("")
        self.res_bar.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.res_bar.setClearButtonEnabled(False)
        self.res_bar.setObjectName("res_bar")
        self.switch_2 = QtWidgets.QPushButton(self.centralwidget)
        self.switch_2.setGeometry(QtCore.QRect(334, 369, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.switch_2.setFont(font)
        self.switch_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_2.setStyleSheet("background-color: rgb(148, 152, 159);\n"
"border: none;\n"
"color: #FFFFFF;")
        self.switch_2.setFlat(False)
        self.switch_2.setObjectName("switch_2")
        self.execute = QtWidgets.QPushButton(self.centralwidget)
        self.execute.setGeometry(QtCore.QRect(334, 569, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execute.sizePolicy().hasHeightForWidth())
        self.execute.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setKerning(True)
        self.execute.setFont(font)
        self.execute.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.execute.setStyleSheet("background-color: rgb(61, 137, 246);\n"
"border: none;color: #FFFFFF;")
        self.execute.setObjectName("execute")
        self.neg = QtWidgets.QPushButton(self.centralwidget)
        self.neg.setEnabled(True)
        self.neg.setGeometry(QtCore.QRect(334, 469, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.neg.setFont(font)
        self.neg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.neg.setStyleSheet("QPushButton {\n"
"    background-color: #94989f;\n"
"border: none;color: #FFFFFF;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7d7d7;\n"
"border: none;\n"
"color: #ececec;\n"
"}")
        self.neg.setObjectName("neg")
        self.to2.raise_()
        self.to10.raise_()
        self.enter_bar.raise_()
        self.num_1.raise_()
        self.num_2.raise_()
        self.num_3.raise_()
        self.num_4.raise_()
        self.num_5.raise_()
        self.num_6.raise_()
        self.num_8.raise_()
        self.num_7.raise_()
        self.num_9.raise_()
        self.dot.raise_()
        self.num_0.raise_()
        self.delete_2.raise_()
        self.switch_2.raise_()
        self.res_bar.raise_()
        self.execute.raise_()
        self.neg.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 456, 24))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet("QMenuBar {\n"
"color:black;\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 lightgray, stop:1 darkgray);\n"
"    spacing: 3px; /* spacing between menu bar items */\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"\n"
"    border-radius: 4px;\n"
"}\n"
"QMenu::item {\n"
"color:black;\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 lightgray, stop:1 darkgray);\n"
"}\n"
"\n"
"QMenu::item:disabled {\n"
"color:gray;\n"
"}")
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuabout = QtWidgets.QMenu(self.menubar)
        self.menuabout.setStyleSheet("color:red;")
        self.menuabout.setSeparatorsCollapsible(True)
        self.menuabout.setObjectName("menuabout")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuPlace = QtWidgets.QMenu(self.menu)
        self.menuPlace.setObjectName("menuPlace")
        self.menuClear = QtWidgets.QMenu(self.menu)
        self.menuClear.setObjectName("menuClear")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setCheckable(True)
        self.actionAuthor.setEnabled(True)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setCheckable(False)
        font = QtGui.QFont()
        self.actionHelp.setFont(font)
        self.actionHelp.setObjectName("actionHelp")
        self.action0 = QtWidgets.QAction(MainWindow)
        self.action0.setEnabled(True)
        self.action0.setObjectName("action0")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.action8 = QtWidgets.QAction(MainWindow)
        self.action8.setObjectName("action8")
        self.action9 = QtWidgets.QAction(MainWindow)
        self.action9.setObjectName("action9")
        self.actionDot = QtWidgets.QAction(MainWindow)
        self.actionDot.setObjectName("actionDot")
        self.actionChar = QtWidgets.QAction(MainWindow)
        self.actionChar.setObjectName("actionChar")
        self.actionAll = QtWidgets.QAction(MainWindow)
        self.actionAll.setObjectName("actionAll")
        self.actionSwitch = QtWidgets.QAction(MainWindow)
        self.actionSwitch.setObjectName("actionSwitch")
        self.actionExecute = QtWidgets.QAction(MainWindow)
        self.actionExecute.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionExecute.setObjectName("actionExecute")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menuabout.addAction(self.actionHelp)
        self.menuabout.addSeparator()
        self.menuPlace.addSeparator()
        self.menuPlace.addAction(self.action0)
        self.menuPlace.addAction(self.action1)
        self.menuPlace.addAction(self.action2)
        self.menuPlace.addAction(self.action3)
        self.menuPlace.addAction(self.action4)
        self.menuPlace.addAction(self.action5)
        self.menuPlace.addAction(self.action6)
        self.menuPlace.addAction(self.action7)
        self.menuPlace.addAction(self.action8)
        self.menuPlace.addAction(self.action9)
        self.menuPlace.addSeparator()
        self.menuPlace.addAction(self.actionDot)
        self.menuPlace.addAction(self.action)
        self.menuClear.addSeparator()
        self.menuClear.addAction(self.actionChar)
        self.menuClear.addAction(self.actionAll)
        self.menu.addAction(self.menuPlace.menuAction())
        self.menu.addAction(self.menuClear.menuAction())
        self.menu.addAction(self.actionSwitch)
        self.menu.addAction(self.actionExecute)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuabout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конвертор чисел"))
        MainWindow.setWhatsThis(_translate("MainWindow", "test"))
        self.to2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#454e59;\">Перевод из 10 в 2</span></p></body></html>"))
        self.to2.setText(_translate("MainWindow", "10->2"))
        self.to10.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#454e59;\">Перевод из 2 в 10</span></p></body></html>"))
        self.to10.setText(_translate("MainWindow", "2->10"))
        self.enter_bar.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#454e59;\">Поле ввода</span></p></body></html>"))
        self.enter_bar.setPlaceholderText(_translate("MainWindow", "Введите число:  "))
        self.num_1.setText(_translate("MainWindow", "1"))
        self.num_2.setText(_translate("MainWindow", "2"))
        self.num_3.setText(_translate("MainWindow", "3"))
        self.num_4.setText(_translate("MainWindow", "4"))
        self.num_5.setText(_translate("MainWindow", "5"))
        self.num_6.setText(_translate("MainWindow", "6"))
        self.num_8.setText(_translate("MainWindow", "8"))
        self.num_7.setText(_translate("MainWindow", "7"))
        self.num_9.setText(_translate("MainWindow", "9"))
        self.dot.setText(_translate("MainWindow", "."))
        self.dot.setShortcut(_translate("MainWindow", ","))
        self.num_0.setText(_translate("MainWindow", "0"))
        self.delete_2.setToolTip(_translate("MainWindow", "Удалить символ перед курсором"))
        self.delete_2.setText(_translate("MainWindow", "C"))
        self.res_bar.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#454e59;\">Результат</span></p></body></html>"))
        self.switch_2.setToolTip(_translate("MainWindow", "Поменять СС"))
        self.switch_2.setText(_translate("MainWindow", "⇆"))
        self.execute.setToolTip(_translate("MainWindow", "Выполнить"))
        self.execute.setText(_translate("MainWindow", "="))
        self.execute.setShortcut(_translate("MainWindow", "Return"))
        self.neg.setText(_translate("MainWindow", "-"))
        self.menuabout.setTitle(_translate("MainWindow", "About"))
        self.menu.setTitle(_translate("MainWindow", "Menu"))
        self.menuPlace.setTitle(_translate("MainWindow", "Place"))
        self.menuClear.setTitle(_translate("MainWindow", "Clear"))
        self.actionAuthor.setText(_translate("MainWindow", "Author"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.action0.setText(_translate("MainWindow", "0"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.action4.setText(_translate("MainWindow", "4"))
        self.action5.setText(_translate("MainWindow", "5"))
        self.action6.setText(_translate("MainWindow", "6"))
        self.action7.setText(_translate("MainWindow", "7"))
        self.action8.setText(_translate("MainWindow", "8"))
        self.action9.setText(_translate("MainWindow", "9"))
        self.actionDot.setText(_translate("MainWindow", "."))
        self.actionChar.setText(_translate("MainWindow", "Char"))
        self.actionChar.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.actionAll.setText(_translate("MainWindow", "All"))
        self.actionSwitch.setText(_translate("MainWindow", "Switch"))
        self.actionSwitch.setShortcut(_translate("MainWindow", "Space"))
        self.actionExecute.setText(_translate("MainWindow", "Execute"))
        self.actionExecute.setShortcut(_translate("MainWindow", "Return"))
        self.action.setText(_translate("MainWindow", "-"))
